// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Person;
@class PersonBuilder;


typedef NS_ENUM(SInt32, Sex) {
  SexFemale = 1,
  SexMale = 2,
};

BOOL SexIsValidValue(Sex value);
NSString *NSStringFromSex(Sex value);


@interface PersonRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Person_name @"name"
#define Person_age @"age"
#define Person_address @"address"
@interface Person : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAge_:1;
  BOOL hasName_:1;
  BOOL hasAddress_:1;
  SInt32 age;
  NSString* name;
  NSString* address;
}
- (BOOL) hasName;
- (BOOL) hasAge;
- (BOOL) hasAddress;
@property (readonly, strong) NSString* name;
@property (readonly) SInt32 age;
@property (readonly, strong) NSString* address;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PersonBuilder*) builder;
+ (PersonBuilder*) builder;
+ (PersonBuilder*) builderWithPrototype:(Person*) prototype;
- (PersonBuilder*) toBuilder;

+ (Person*) parseFromData:(NSData*) data;
+ (Person*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Person*) parseFromInputStream:(NSInputStream*) input;
+ (Person*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PersonBuilder : PBGeneratedMessageBuilder {
@private
  Person* resultPerson;
}

- (Person*) defaultInstance;

- (PersonBuilder*) clear;
- (PersonBuilder*) clone;

- (Person*) build;
- (Person*) buildPartial;

- (PersonBuilder*) mergeFrom:(Person*) other;
- (PersonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PersonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (PersonBuilder*) setName:(NSString*) value;
- (PersonBuilder*) clearName;

- (BOOL) hasAge;
- (SInt32) age;
- (PersonBuilder*) setAge:(SInt32) value;
- (PersonBuilder*) clearAge;

- (BOOL) hasAddress;
- (NSString*) address;
- (PersonBuilder*) setAddress:(NSString*) value;
- (PersonBuilder*) clearAddress;
@end


// @@protoc_insertion_point(global_scope)
